from lxml import etree

with open("show_security_zones.xml") as f:
    xml_file = f.read()

my_xml = etree.fromstring(xml_file)

print("=" * 50)
print("Exercise 1a")
print("=" * 50)
print()
print(my_xml)
print(type(my_xml))
print()

print("=" * 50)
print("Exercise 1b")
print("=" * 50)
print()
print(etree.tostring(my_xml).decode())
print()
print("=" * 50)
print("Exercise 1c")
print("=" * 50)
print()
print(my_xml.tag)
print()
print("-" * 20)
print("Amount of children")
print("-" * 20)
print()
print(len(my_xml))
print()
print("=" * 50)
print("Exercise 1d")
print("=" * 50)
print()
print(my_xml.getchildren()[0].tag)
print()
print("=" * 50)
print("Exercise 1e")
print("=" * 50)
print()
trust_zone = my_xml.getchildren()[0]
print(trust_zone[0].text)
print()
print("=" * 50)
print("Exercise 1f")
print("=" * 50)
print()
for children in trust_zone:
    print(children.tag)
print()
